**NUMPY UFUNC**

***CREATING UFUNC***

In [3]:
import numpy as np 

In [5]:
def myadd(x,y):
    return x+y
myadd=np.frompyfunc(myadd,2,1)#2 is input and 1 is output
print(myadd([1,2,3,4,5],[5,6,7,8,9]))
print(type(np.add))#prints the type of add

[6 8 10 12 14]
<class 'numpy.ufunc'>


In [7]:
#to check func is universal or not 
if type(np.add)==np.ufunc:
    print('add is ufunc.')
else:
    print('add is npot ufunc')

add is ufunc.


***SIMPLE ARITHMETIC***

In [10]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,6,7,8,9])
add=np.add(arr1,arr2)
sub=np.subtract(arr2,arr1)
mul=np.multiply(arr1,arr2)
div=np.divide(arr1,arr2)
print(add)
print(sub)
print(mul)
print(div)

[ 6  8 10 12 14]
[4 4 4 4 4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [12]:
scalar_multiply=np.multiply(arr1,2)
print(scalar_multiply)

[ 2  4  6  8 10]


***ROUNDING DECIMAL***

In [16]:
div=np.divide(arr1,arr2)
print(np.round(div, decimals=2))

[0.2  0.33 0.43 0.5  0.56]


In [18]:
around_div=np.around(div,decimals=1)
print(around_div)

[0.2 0.3 0.4 0.5 0.6]


***LOGS***

In [21]:
#LOGRITHM FUNTION IS NUMPY UNIVERSAL FUNCTION AT 
#BACKBONE OF THE OPERATIONS IN PYTHON.
num=np.array([1,2,3,4,5])
print(np.log(num))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
#for exponential result
print(np.exp(num))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [25]:
#for log base 10 result 
print(np.log10(num))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


***SUMMATIONS***

In [32]:
#SUMMATIONS IS THE FUNDAMENTAL OPERATION FOR DATA MANIPULATION AND ANALYSIS
data_array=np.array([10,20,30,40,50])
print(np.sum(data_array))

150


In [61]:
#creating summation with along axis
axis_sum=np.sum(data_array,axis=0)#summation along row 
print(axis_sum)

150


In [48]:
data=np.array([[1,2,3],[4,5,6]])
axis_sum=np.sum(data,axis=1)#summation along row
print(axis_sum)

[ 6 15]


In [50]:
data=np.array([[1,2,3],[4,5,6]])
axis_sum=np.sum(data,axis=0)#summation along column
print(axis_sum)

[5 7 9]


In [56]:
#cummulative sum funtion 
#cumcum() method is used to add the terms in consecutive way such that
#eg [1,2,3,4]---->[1,1+2,1+2+3,1+2+3+4]----->[1,3,6,10]
data_array=np.array([10,20,30,40,50])
print(np.cumsum(data_array))

[ 10  30  60 100 150]


***PRODUCTS***

In [59]:
#PRODUCT FUNCTION PRODUCTS THE NUMBER OF ELEMENT PRESENT IN ARRAY
#WITH THE HELP OF prod() METHOD WE CALCULATE THE PRODUCT OF AN ARRAY ELEMENTS
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.prod(arr))

3628800


In [63]:
#product along axis
axis_prod=np.prod(arr,axis=0)
print(axis_prod)

3628800


In [71]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#along axis=0-->column
axis_prod=np.prod(arr,axis=0)
print(axis_prod)
#along axis=1-->row
axis_prod1=np.prod(arr,axis=1)
print(axis_prod1)

[ 6 14 24 36 50]
[  120 30240]


In [73]:
#cummulative product-->cumprod() method is used
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.cumprod(arr))

[      1       2       6      24     120     720    5040   40320  362880
 3628800]
