In [2]:
import numpy as np 

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**Dimension in array**

In [9]:
c=np.array(20)#0d array
print(c)
print(type(c))
print(c.ndim)#ndim for printing the dimenstion of array

20
<class 'numpy.ndarray'>
0


In [11]:
d=np.array([1,2,3,4,5])#1d array
print(d)
print(type(d))
print(d.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [13]:
#2d array
e=np.array([[1,2],[3,4],[5,6],[7,8]])
print(e)
print(e.ndim)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
2


In [15]:
#3d array
f=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(f)
print(f.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


**NUMPY ARRAY INDEXING**

In [18]:
c=np.array([1,2,3,4])
print(c[0])

1


Array indexing is same as finding an array element.

In [21]:
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Second element on 1st row:",c[0,1])
print("Second element on 2nd row:",c[1,1])

Second element on 1st row: 2
Second element on 2nd row: 7


In [23]:
#adding the 1st elemnt of row 1 and last elemnt of row 2
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("First element on 1st row:",c[0,0])
print("Last element on 2nd row:",c[1,4])
print("Sum is ",c[0,0]+c[1,4])

First element on 1st row: 1
Last element on 2nd row: 10
Sum is  11


In [25]:
#accessing the third element of second array of first array
f=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(f[0,1,2])

6


**SLICING OF NUMPY ARRAY**

In [28]:
#2d array slicing
p=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(p[1,1:4])
#1 is [6,7,8,9,10]
#1:4 is the range to find the value in range (0,4)
#overall it means is slicing element in 1 element list.

[7 8 9]


In [30]:
#3d array slicing
f=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(f[0,1,0:3])
#here 0 is [[1,2,3],[4,5,6]] 
#1 is [4,5,6]
#0:3 is the indexing done to get the values output in range(0,3)

[4 5 6]


In [32]:
#1d array slicing
c=np.array([1,2,3,4])
print(c[0:3])

[1 2 3]


In [34]:
#1d array slicing
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12,14,15])
print(c[0:13:2])
#o is starting index
#13 is the ending of index till where we want slicing
#2 is the step

[ 1  3  5  7  9 11 14]


**CHECKING THE DATATYPE OF AN ARRAY**

In [37]:
A=np.array([1,2,3,4,5])
a=np.array(['animal','birds','plants','seahoreses'])
print(A.dtype)
print(a.dtype)#data is of type unicode 10


int32
<U10


**CREATING ARRAY WITH DEFINED DATATYPE**

In [40]:
b=np.array([1,2,3,4],dtype='S')
#here S is for string so output is converted to string type.
print(b)
print(b.dtype)

[b'1' b'2' b'3' b'4']
|S1


**CREATE ARRAY WITH DATATYPE 4 BYTE INTEGER**

In [43]:
c=np.array([1,2,3,4],dtype='i4')
print(c)
print(c.dtype)

[1 2 3 4]
int32


**NUMPY ARRAY SHAPE**

THE SHAPE OF AN ARRAY IS THE NUMBER OF ELEMENT IN EACH DIMENSION.

In [47]:
p=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(p.shape)

(2, 5)


In [49]:
f=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(f.shape)

(2, 2, 3)


**JOINING TWO NUMPY ARRAY**

In [52]:
#1d array concatination
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [54]:
#2d array concatination
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[5,6,7],[7,8,9]])
arr=np.concatenate((arr1,arr2),axis=1)
#1 leads to concatenation along row
arr3=np.concatenate((arr1,arr2),axis=0)
#0 leads to concatenation along column
print(arr)
print(arr3)

[[1 2 3 5 6 7]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [5 6 7]
 [7 8 9]]


**SPLITTING NUMPY ARRAYS**

In [57]:
#Splitting the array in 3 parts :
c=np.array([1,2,3,4,5,6])
d=np.array_split(c,3)
#here 3 is the no of parts
print(d)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [59]:
#splitting array in 4 parts
c=np.array([1,2,3,4,5,6])
d=np.array_split(c,4)
#here 4 is the no of parts
print(d)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


**RAVEL AND FLATTEN FUNCTION**

In [62]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print(m.ndim)
n=m.ravel()
print(n)
print("now the new dimension is",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [64]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print(m.ndim)
n=m.flatten()
print(n)
print("now the new dimension is",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [66]:
m=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(m)
print(m.ndim)
n=m.flatten()
print(n)
print("now the new dimension is",n.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


**UNIQUE FUNCTION**

In [69]:
k=np.array([1,8,5,9,5,9,6,4,8,3,2,1,2,9,7])
print(k)
x=np.unique(k)
print(x)

[1 8 5 9 5 9 6 4 8 3 2 1 2 9 7]
[1 2 3 4 5 6 7 8 9]


In [71]:
k=np.array([1,8,5,9,5,9,6,4,8,3,2,1,2,9,7])
print(k)
x=np.unique(k,return_index=True)
print(x)

[1 8 5 9 5 9 6 4 8 3 2 1 2 9 7]
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0, 10,  9,  7,  2,  6, 14,  1,  3], dtype=int64))


In [73]:
k=np.array([1,8,5,9,5,9,6,4,8,3,2,1,2,9,7])
print(k)
x=np.unique(k,return_index=True,return_counts=True)
print(x)

[1 8 5 9 5 9 6 4 8 3 2 1 2 9 7]
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([ 0, 10,  9,  7,  2,  6, 14,  1,  3], dtype=int64), array([2, 2, 1, 1, 2, 1, 1, 2, 3], dtype=int64))


**DELETE FUNCTION**

In [76]:
a=np.array([12,13,14,15,16])
d=np.delete(a,[2])
print(d)

[12 13 15 16]


In [78]:
x=np.array([[2,7,6,8,9],[3,4,5,7,1],[16,17,18,19,20]])
print(x)
y=np.delete(x,1,axis=0)
#delete the complete list at index 1
print(y)

[[ 2  7  6  8  9]
 [ 3  4  5  7  1]
 [16 17 18 19 20]]
[[ 2  7  6  8  9]
 [16 17 18 19 20]]


In [80]:
x_flat=x.flatten()
#flatten converts the array into 1d array
x_flat=np.delete(x_flat,5)
print(x_flat)

[ 2  7  6  8  9  4  5  7  1 16 17 18 19 20]


In [82]:
x = x_flat.reshape(2, 7)

print(x)

[[ 2  7  6  8  9  4  5]
 [ 7  1 16 17 18 19 20]]


**COPY FUNCTION**

In [85]:
#copy function copy the array in another array where called and if change is 
#made in copied array the will not be made in original array
original_array=np.array([1,2,3,4,5])
coppied_array=original_array.copy()
coppied_array[0]=9
print(original_array)
print(coppied_array)

[1 2 3 4 5]
[9 2 3 4 5]


**VIEW FUNCTION**

In [88]:
#view function makes change in array_view as well in original_array
original_array=np.array([1,2,3,4,5])
array_view=original_array.view()
array_view[0]=9
print(original_array)
print(array_view)

[9 2 3 4 5]
[9 2 3 4 5]
